name: pdm
description: psdk download manager
version: 1.0.0
homepage: https://github.com/psdk/pdm
repository: https://github.com/psdk/pdm
issue_tracker: https://github.com/psdk/pdm/issues

environment:
  sdk: ^3.5.0
