import 'dart:io';

import '../../config.dart' show homeDir;
import '../context.dart';
import '../flags.dart';
import '../help.dart' show commandInfo;
import '../parser.dart';

const Set<String> _idPositionalCommands = {
  'pause',
  'resume',
  'cancel',
  'remove',
  'watch',
};

Future<int> runCompletion(CliContext ctx, ParsedArgs args) async {
  var shell = args.positionals.isNotEmpty ? args.positionals.first : null;
  if (shell == null) {
    shell = _detectShell();
    if (shell == null) {
      stderr.writeln('Usage: pdm completion <bash|zsh> [--print] [--user]');
      stderr.writeln(
        'Could not auto-detect your shell from \$SHELL; please pass it explicitly.',
      );
      return 1;
    }
    ctx.log('Detected shell: $shell');
  }
  if (shell != 'bash' && shell != 'zsh') {
    stderr.writeln('Usage: pdm completion <bash|zsh> [--print] [--user]');
    return 1;
  }
  final script = shell == 'bash' ? _bashScript() : _zshScript();
  if (args.flag('print') || Platform.isWindows) {
    stdout.writeln(script);
    if (Platform.isWindows && !args.flag('print')) {
      ctx.log(
        'Automatic install is only supported on Linux/macOS; pipe this into your shell config, e.g.:',
      );
      ctx.log('  pdm completion $shell >> ~/.bashrc');
    }
    return 0;
  }
  final forceUser = args.flag('user');
  final target = _targetPath(shell, forceUser: forceUser);
  try {
    final file = File(target);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(script);
    ctx.log(ctx.theme.success('Installed $shell completions to $target'));
    if (shell == 'bash' && !forceUser) {
      ctx.log('Restart your shell, or run: source $target');
    } else if (shell == 'zsh' && !forceUser) {
      ctx.log('Restart your shell, or run: autoload -U compinit && compinit');
    }
    return 0;
  } on FileSystemException {
    final systemTarget = _targetPath(shell, forceUser: false);
    stderr.writeln(
      ctx.theme.error('Could not write to $systemTarget (permission denied).'),
    );
    stderr.writeln('Run this to install system-wide:');
    stderr.writeln('  sudo pdm completion $shell');
    stderr.writeln('Or install it for your user only:');
    stderr.writeln('  pdm completion $shell --user');
    return 1;
  }
}

String? _detectShell() {
  final shellPath = Platform.environment['SHELL'];
  if (shellPath == null || shellPath.isEmpty) return null;
  final base = shellPath.split(RegExp(r'[\\/]')).last;
  if (base == 'bash' || base == 'zsh') return base;
  return null;
}

String _targetPath(String shell, {required bool forceUser}) {
  if (forceUser) {
    final base = homeDir();
    return shell == 'bash'
        ? '$base/.local/share/bash-completion/completions/pdm'
        : '$base/.local/share/zsh/site-functions/_pdm';
  }
  return shell == 'bash'
      ? '/usr/share/bash-completion/completions/pdm'
      : '/usr/share/zsh/site-functions/_pdm';
}

Map<String, String> _aliasMap() {
  final map = <String, String>{};
  for (final name in commandFlags.keys) {
    map[name] = name;
  }
  commandInfo.forEach((name, info) {
    map[name] = name;
    for (final alias in info.aliases) {
      map[alias] = name;
    }
  });
  return map;
}

List<MapEntry<String, String>> _commandEntries() {
  final list = <MapEntry<String, String>>[];
  commandInfo.forEach((name, info) {
    list.add(MapEntry(name, info.summary));
    for (final alias in info.aliases) {
      list.add(MapEntry(alias, '${info.summary} (alias for "$name")'));
    }
  });
  list.add(const MapEntry('version', 'Print the pdm version'));
  list.add(
    const MapEntry('help', 'Show help, or help for one command'),
  );
  return list;
}

String _flagSpecEntry(FlagDef f) {
  final kind = f.kind == FlagKind.flag ? 'flag' : 'val';
  String value;
  if (f.kind == FlagKind.flag) {
    value = '';
  } else if (f.choices.isNotEmpty) {
    value = 'enum:${f.choices.join(',')}';
  } else if (f.isPath) {
    value = 'path';
  } else {
    value = 'plain';
  }
  final desc = f.help.replaceAll('|', '/').replaceAll(';', ',');
  return '${f.short}|${f.long}|$kind|${f.conflicts.join(',')}|$value|$desc';
}

String _flagSetSpec(List<FlagDef> flags) =>
    flags.map(_flagSpecEntry).join(';');

String _positionalKind(String canonical) {
  if (_idPositionalCommands.contains(canonical)) return 'ids';
  final choices = commandPositionalChoices[canonical];
  if (choices != null) return 'enum:${choices.keys.join(',')}';
  return 'none';
}

String _shellIdentifier(String command) =>
    command.toUpperCase().replaceAll('-', '_');

String _shQuote(String s) => s.replaceAll("'", r"'\''");

String _bashScript() {
  final buf = StringBuffer();
  buf.writeln('# pdm bash completion — generated by "pdm completion bash".');
  buf.writeln(
    '# Commands, flags, value choices, and flag conflicts are read straight',
  );
  buf.writeln(
    '# from pdm\'s own flag definitions, so this stays accurate across',
  );
  buf.writeln(
    '# versions. Descriptions aren\'t shown here (a bash limitation) — see',
  );
  buf.writeln('# "pdm completion zsh" for completions with descriptions.');
  buf.writeln();

  final commandWords = _commandEntries().map((e) => e.key).join(' ');
  buf.writeln("ALL_COMMANDS='${_shQuote(commandWords)}'");
  buf.writeln();

  for (final name in commandFlags.keys) {
    final spec = _flagSetSpec([...globalFlags, ...commandFlags[name]!]);
    buf.writeln("SPEC_${_shellIdentifier(name)}='${_shQuote(spec)}'");
  }
  buf.writeln();

  buf.writeln(r'''
_pdm_ids() {
  local out
  out=$(command pdm list --json 2>/dev/null) || return 0
  printf '%s' "$out" | grep -oE '"id":"[^"]*"' | sed -E 's/^"id":"//; s/"$//'
}

_pdm_short_for() {
  local spec="$1" longwant="$2"
  local IFS=';'
  local -a entries=($spec)
  local e short long kind conflicts value desc
  for e in "${entries[@]}"; do
    IFS='|' read -r short long kind conflicts value desc <<< "$e"
    if [ "$long" = "$longwant" ]; then printf '%s' "$short"; return 0; fi
  done
}

_pdm_value_kind_for() {
  local spec="$1" prev="$2"
  local IFS=';'
  local -a entries=($spec)
  local e short long kind conflicts value desc
  for e in "${entries[@]}"; do
    IFS='|' read -r short long kind conflicts value desc <<< "$e"
    if [ "$prev" = "-$short" ] || [ "$prev" = "--$long" ]; then
      if [ "$kind" = "val" ]; then printf '%s' "$value"; fi
      return 0
    fi
  done
}

_pdm_available_flags() {
  local spec="$1" used="$2"
  local IFS=';'
  local -a entries=($spec)
  local e short long kind conflicts value desc
  local out=""
  for e in "${entries[@]}"; do
    IFS='|' read -r short long kind conflicts value desc <<< "$e"
    if [[ " $used " == *" -$short "* ]] || [[ " $used " == *" --$long "* ]]; then
      continue
    fi
    local skip=0
    if [ -n "$conflicts" ]; then
      local c
      for c in ${conflicts//,/ }; do
        local cs
        cs=$(_pdm_short_for "$spec" "$c")
        if [[ " $used " == *" --$c "* ]] || { [ -n "$cs" ] && [[ " $used " == *" -$cs "* ]]; }; then
          skip=1
          break
        fi
      done
    fi
    [ "$skip" = 1 ] && continue
    out="$out -$short --$long"
  done
  printf '%s' "$out"
}

_pdm_positional_count() {
  local spec="$1"; shift
  local -a ws=("$@")
  local count=0 i=0
  local n=${#ws[@]}
  while [ $i -lt $n ]; do
    local w="${ws[$i]}"
    if [[ "$w" == -* ]]; then
      local vk
      vk=$(_pdm_value_kind_for "$spec" "$w")
      if [ -n "$vk" ]; then
        i=$((i+2))
      else
        i=$((i+1))
      fi
    else
      count=$((count+1))
      i=$((i+1))
    fi
  done
  printf '%s' "$count"
}
''');

  buf.writeln('_pdm_canon() {');
  buf.writeln('  case "\$1" in');
  final aliasMap = _aliasMap();
  for (final entry in aliasMap.entries) {
    if (entry.key == entry.value) continue;
    buf.writeln('    ${entry.key}) echo ${entry.value} ;;');
  }
  buf.writeln('    *) echo "\$1" ;;');
  buf.writeln('  esac');
  buf.writeln('}');
  buf.writeln();

  buf.writeln('_pdm_positional_kind() {');
  buf.writeln('  case "\$1" in');
  for (final name in commandFlags.keys) {
    buf.writeln('    $name) echo "${_positionalKind(name)}" ;;');
  }
  buf.writeln('    *) echo "none" ;;');
  buf.writeln('  esac');
  buf.writeln('}');
  buf.writeln();

  buf.writeln('_pdm_flagset() {');
  buf.writeln('  case "\$1" in');
  for (final name in commandFlags.keys) {
    buf.writeln('    $name) echo "\$SPEC_${_shellIdentifier(name)}" ;;');
  }
  buf.writeln('    *) echo "" ;;');
  buf.writeln('  esac');
  buf.writeln('}');
  buf.writeln();

  buf.writeln(r'''
_pdm_completions() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=()

  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$ALL_COMMANDS" -- "$cur") )
    return 0
  fi

  local typed="${COMP_WORDS[1]}"
  local canon
  canon=$(_pdm_canon "$typed")
  local prev="${COMP_WORDS[COMP_CWORD-1]}"
  local spec
  spec=$(_pdm_flagset "$canon")

  # 1) value completion if the previous word is a flag expecting one
  local vk
  vk=$(_pdm_value_kind_for "$spec" "$prev")
  if [ -n "$vk" ]; then
    case "$vk" in
      path)
        COMPREPLY=( $(compgen -f -- "$cur") )
        ;;
      enum:*)
        local choices="${vk#enum:}"
        COMPREPLY=( $(compgen -W "${choices//,/ }" -- "$cur") )
        ;;
      *) : ;; # plain value, nothing sensible to suggest
    esac
    return 0
  fi

  local -a usedwords=("${COMP_WORDS[@]:2:COMP_CWORD-2}")
  local used=" ${usedwords[*]} "

  # 2) if the user is typing a flag, only offer flags that are still legal
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$(_pdm_available_flags "$spec" "$used")" -- "$cur") )
    return 0
  fi

  # 3) otherwise offer this command's positional completion, if any
  local pk
  pk=$(_pdm_positional_kind "$canon")
  case "$pk" in
    ids)
      COMPREPLY=( $(compgen -W "$(_pdm_ids)" -- "$cur") )
      ;;
    enum:*)
      local poscount
      poscount=$(_pdm_positional_count "$spec" "${usedwords[@]}")
      if [ "$poscount" -eq 0 ]; then
        local choices="${pk#enum:}"
        COMPREPLY=( $(compgen -W "${choices//,/ }" -- "$cur") )
      else
        COMPREPLY=( $(compgen -W "$(_pdm_available_flags "$spec" "$used")" -- "$cur") )
      fi
      ;;
    *)
      COMPREPLY=( $(compgen -W "$(_pdm_available_flags "$spec" "$used")" -- "$cur") )
      ;;
  esac
}
complete -F _pdm_completions pdm
''');
  return buf.toString();
}

String _zshScript() {
  final buf = StringBuffer();
  buf.writeln('#compdef pdm');
  buf.writeln('# pdm zsh completion — generated by "pdm completion zsh".');
  buf.writeln(
    '# Commands, flags, value choices, flag conflicts and descriptions are',
  );
  buf.writeln(
    '# read straight from pdm\'s own flag definitions, so this stays',
  );
  buf.writeln('# accurate across versions.');
  buf.writeln();

  buf.write('ALL_COMMANDS_DESC=(\n');
  for (final entry in _commandEntries()) {
    buf.writeln("  '${entry.key}:${_shQuote(entry.value)}'");
  }
  buf.writeln(')');
  buf.writeln();

  for (final name in commandFlags.keys) {
    final spec = _flagSetSpec([...globalFlags, ...commandFlags[name]!]);
    buf.writeln("SPEC_${_shellIdentifier(name)}='${_shQuote(spec)}'");
  }
  buf.writeln();

  buf.writeln(r'''
_pdm_ids() {
  local json
  json=$(command pdm list --json 2>/dev/null) || return
  local -a ids stats
  ids=(${(f)"$(printf '%s' "$json" | grep -oE '"id":"[^"]*"' | sed -E 's/^"id":"//; s/"$//')"})
  stats=(${(f)"$(printf '%s' "$json" | grep -oE '"status":"[^"]*"' | sed -E 's/^"status":"//; s/"$//')"})
  (( ${#ids[@]} )) || return
  local -a items
  local i
  for (( i = 1; i <= ${#ids[@]}; i++ )); do
    items+=("${ids[i]}:${stats[i]:-unknown}")
  done
  _describe -t pdm-ids 'task id' items
}

_pdm_short_for() {
  local spec="$1" longwant="$2"
  local -a entries; entries=(${(s:;:)spec})
  local e
  for e in "${entries[@]}"; do
    local -a f; f=(${(s:|:)e})
    if [[ "${f[2]}" == "$longwant" ]]; then
      print -r -- "${f[1]}"
      return 0
    fi
  done
}

_pdm_value_kind_for() {
  local spec="$1" prev="$2"
  local -a entries; entries=(${(s:;:)spec})
  local e
  for e in "${entries[@]}"; do
    local -a f; f=(${(s:|:)e})
    local short="${f[1]}" long="${f[2]}" kind="${f[3]}"
    if [[ "$prev" == "-$short" || "$prev" == "--$long" ]]; then
      [[ "$kind" == "val" ]] && print -r -- "${f[5]}"
      return 0
    fi
  done
  return 1
}

# Prints one "word:description" line per still-legal flag, for _describe.
_pdm_available_flags() {
  local spec="$1" used="$2"
  local -a entries; entries=(${(s:;:)spec})
  local e
  local -a out
  for e in "${entries[@]}"; do
    local -a f; f=(${(s:|:)e})
    local short="${f[1]}" long="${f[2]}" conflicts="${f[4]}" desc="${f[6]}"
    if [[ " $used " == *" -$short "* || " $used " == *" --$long "* ]]; then
      continue
    fi
    local skip=0
    if [[ -n "$conflicts" ]]; then
      local c
      for c in ${(s:,:)conflicts}; do
        local cs
        cs=$(_pdm_short_for "$spec" "$c")
        if [[ " $used " == *" --$c "* || ( -n "$cs" && " $used " == *" -$cs "* ) ]]; then
          skip=1
          break
        fi
      done
    fi
    (( skip )) && continue
    out+=("-$short:$desc" "--$long:$desc")
  done
  (( ${#out[@]} )) && print -rl -- "${out[@]}"
}

_pdm_positional_count() {
  local spec="$1"; shift
  local -a ws=("$@")
  local count=0 i=1
  while (( i <= $#ws )); do
    local w="${ws[i]}"
    if [[ "$w" == -* ]]; then
      local vk
      vk=$(_pdm_value_kind_for "$spec" "$w")
      if [[ -n "$vk" ]]; then
        i=$(( i + 2 ))
      else
        i=$(( i + 1 ))
      fi
    else
      count=$(( count + 1 ))
      i=$(( i + 1 ))
    fi
  done
  print -r -- "$count"
}

_pdm_describe_flags() {
  local spec="$1" used="$2"
  local -a flagdesc
  flagdesc=(${(f)"$(_pdm_available_flags "$spec" "$used")"})
  (( ${#flagdesc[@]} )) && _describe -t pdm-flags 'flag' flagdesc
}
''');

  buf.writeln('_pdm_canon() {');
  buf.writeln('  case "\$1" in');
  final aliasMap = _aliasMap();
  for (final entry in aliasMap.entries) {
    if (entry.key == entry.value) continue;
    buf.writeln('    ${entry.key}) echo ${entry.value} ;;');
  }
  buf.writeln('    *) echo "\$1" ;;');
  buf.writeln('  esac');
  buf.writeln('}');
  buf.writeln();

  buf.writeln('_pdm_positional_kind() {');
  buf.writeln('  case "\$1" in');
  for (final name in commandFlags.keys) {
    buf.writeln('    $name) echo "${_positionalKind(name)}" ;;');
  }
  buf.writeln('    *) echo "none" ;;');
  buf.writeln('  esac');
  buf.writeln('}');
  buf.writeln();

  buf.writeln('_pdm_flagset() {');
  buf.writeln('  case "\$1" in');
  for (final name in commandFlags.keys) {
    buf.writeln('    $name) echo "\$SPEC_${_shellIdentifier(name)}" ;;');
  }
  buf.writeln('    *) echo "" ;;');
  buf.writeln('  esac');
  buf.writeln('}');
  buf.writeln();

  buf.writeln('_pdm_positional_items() {');
  buf.writeln('  local -a items');
  buf.writeln('  case "\$1" in');
  for (final entry in commandPositionalChoices.entries) {
    buf.writeln('    ${entry.key})');
    buf.writeln('      items=(');
    for (final choice in entry.value.entries) {
      buf.writeln(
        "        '${choice.key}:${_shQuote(choice.value)}'",
      );
    }
    buf.writeln('      )');
    buf.writeln('      ;;');
  }
  buf.writeln('  esac');
  buf.writeln(
    '  (( \${#items[@]} )) && _describe -t pdm-actions \'action\' items',
  );
  buf.writeln('}');
  buf.writeln();

  buf.writeln(r'''
_pdm() {
  local cur="${words[CURRENT]}"

  if (( CURRENT == 2 )); then
    _describe -t pdm-commands 'pdm command' ALL_COMMANDS_DESC
    return
  fi

  local typed="${words[2]}"
  local canon
  canon=$(_pdm_canon "$typed")
  local prev="${words[CURRENT-1]}"
  local spec
  spec=$(_pdm_flagset "$canon")

  # 1) value completion if the previous word is a flag expecting one
  local vk
  vk=$(_pdm_value_kind_for "$spec" "$prev")
  if [[ -n "$vk" ]]; then
    case "$vk" in
      path)
        _files
        ;;
      enum:*)
        local raw="${vk#enum:}"
        local -a choices
        choices=(${(s:,:)raw})
        _describe -t pdm-values 'value' choices
        ;;
      *) ;; # plain value, nothing sensible to suggest
    esac
    return
  fi

  local -a usedwords
  usedwords=(${words[3,CURRENT-1]})
  local used=" ${(j: :)usedwords} "

  # 2) if the user is typing a flag, only offer flags that are still legal
  if [[ "$cur" == -* ]]; then
    _pdm_describe_flags "$spec" "$used"
    return
  fi

  # 3) otherwise offer this command's positional completion, if any
  local pk
  pk=$(_pdm_positional_kind "$canon")
  case "$pk" in
    ids)
      _pdm_ids
      ;;
    enum:*)
      local poscount
      poscount=$(_pdm_positional_count "$spec" "${usedwords[@]}")
      if (( poscount == 0 )); then
        _pdm_positional_items "$canon"
      else
        _pdm_describe_flags "$spec" "$used"
      fi
      ;;
    *)
      _pdm_describe_flags "$spec" "$used"
      ;;
  esac
}

_pdm "$@"
''');
  return buf.toString();
}
